[package]
name = "polkadot-introspector"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
log = "0.4.17"
color-eyre = "0.6.0"
clap = {version = "3.1.0", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
subxt = { git = "https://github.com/paritytech/subxt", branch = "master" }
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread", "signal"] }
typed-builder = "0.10"
futures = "0.3.21"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "master" }
warp = { version = "0.3", features = ["tls"] }
reqwest = { version = "0.11.11" }
rasciigraph = "0.1.1"
crossterm = "0.23.0"
colored = "2.0.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_bytes = "0.11"
serde_urlencoded = "0.7.1"
async-trait = "0.1.52"
strum = { version = "0.24.1", features = ["derive"] }
rocksdb = "0.18.0"
parity-db = "0.3.14"

