[package]
name = "polkadot-introspector"
version = "0.1.1"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
color-eyre = "0.6.2"
clap = {version = "4.1.8", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive", "full", "bit-vec"] }
subxt = { git = "https://github.com/paritytech/subxt", rev = "v0.27.1" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "signal"] }
thiserror = "1.0.38"
typed-builder = "0.12.0"
futures = "0.3.26"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "master" }
warp = { version = "0.3.3", features = ["tls"] }
reqwest = { version = "0.11.14" }
rasciigraph = "0.2.0"
crossterm = "0.26.1"
colored = "2.0.0"
serde = "1.0.152"
serde_json = "1.0.93"
serde_derive = "1.0.138"
serde_bytes = "0.11.9"
serde_urlencoded = "0.7.1"
bincode = "1.3.3"
erased-serde = "0.3.25"
async-trait = "0.1.64"
strum = { version = "0.24.1", features = ["derive"] }
rocksdb = "0.20.1"
parity-db = "0.4.3"
hex = "0.4.3"
itertools = "0.10.5"
snap = "1.1.0"
rand = "0.8.5"
time = { version = "0.3.20", features = ["formatting"] }

[features]
#default = ["versi"]
rococo = []
polkadot = []
versi = []
