[package]
name = "polkadot-introspector"
version = "0.1.1"
edition = "2021"

[dependencies]
env_logger = "0.9.3"
log = "0.4.17"
color-eyre = "0.6.2"
clap = {version = "4.0.25", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
subxt = { git = "https://github.com/paritytech/subxt", rev = "c55b7ba3e34118f61dc51499a0b38262c513aec4" }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"] }
typed-builder = "0.11.0"
futures = "0.3.25"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "master" }
warp = { version = "0.3.3", features = ["tls"] }
reqwest = { version = "0.11.12" }
rasciigraph = "0.1.1"
crossterm = "0.25.0"
colored = "2.0.0"
serde = "1.0.147"
serde_json = "1.0.87"
serde_derive = "1.0.138"
serde_bytes = "0.11.7"
serde_urlencoded = "0.7.1"
bincode = "1.3.3"
erased-serde = "0.3.23"
async-trait = "0.1.58"
strum = { version = "0.24.1", features = ["derive"] }
rocksdb = "0.19.0"
parity-db = "0.4.2"
hex = "0.4.3"
itertools = "0.10.5"
snap = "1.0.5"
rand = "0.8.5"
time = { version = "0.3.17", features = ["formatting"] }