[workspace]
members = [
    "block-time",
    "essentials",
    "jaeger",
    "kvdb",
    "metadata-checker",
    "parachain-tracer",
    "priority-channel",
    "whois",
]

[workspace.package]
version = "0.2.4"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paritytech/polkadot-introspector"
