[workspace]

members = ["priority-channel", "essentials", "introspector"]

[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
version = "0.1.0"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paritytech/polkadot-introspector"
