[package]
name = "priority-channel"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Channels with message prioritization"
repository = "https://github.com/paritytech/polkadot-introspector.git"
license = "MIT OR Apache-2.0"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
async-channel = "1.8.0"
derive_more = "0.99"
tracing = "0.1.35"
thiserror = "1.0.31"
rand = "0.8.5"

[dev-dependencies]
tokio = { version = "1.27.0", features = ["macros", "rt"] }
