{
 "title": "Granular Node DB metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "chain",
    "query": {
     "query": "introspector_kvdb_values_size{}"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "introspector_kvdb_values_size{}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[${chain}] ${database} per column value usage",
   "type": "timeseries",
   "description": "This panel shows the usage of each column value in the database. This is useful to see if there are any column values that are using a lot of space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(introspector_kvdb_values_size{chain=\"$chain\", container=\"$database\"}) by (column)",
     "legendFormat": "{{column}}"
    }
   ]
  },
  {
   "title": "[${chain}] ${database} per column key usage",
   "type": "timeseries",
   "description": "This panel shows the per column key usage for the selected database. This is useful to see if there are any keys that are using a lot of space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(introspector_kvdb_keys_size{chain=\"$chain\", container=\"$database\"}) by (column)",
     "legendFormat": "{{column}}"
    }
   ]
  },
  {
   "title": "[${chain}] ${database} per column entry count",
   "type": "timeseries",
   "description": "This panel shows the number of entries per column in the database. This is useful to see if there are any columns that have a lot of entries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(introspector_kvdb_elements_count{chain=\"$chain\", container=\"$database\"}) by (column)",
     "legendFormat": "{{column}}"
    }
   ]
  }
 ]
}