[package]
name = "polkadot-whois"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
color-eyre = "0.6.2"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.17"
polkadot-introspector-essentials = { path = "../essentials" }
polkadot-introspector-priority-channel = { path = "../priority-channel" }
thiserror = "1.0.39"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "signal"] }
