[relaychain]
default_command = "polkadot"
chain = "polkadot-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = {{ZOMBIE_WS_PORT}}

  [[relaychain.node_groups]]
  name = "validator"
  count = 4

[[parachains]]
id = 2000

  [parachains.collator]
  name = "collator"
