[relaychain]
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 65000

  [[relaychain.node_groups]]
  name = "validator"
  count = 4

[[parachains]]
id = 2000

  [parachains.collator]
  name = "collator"
