name: Check updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

env:
  BRANCH_NAME: automated-update-metadata

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Try to checkout existing PR branch
        id: checkout-pr
        run: |
          EXISTING_BRANCH=$(git branch -r --list "origin/$BRANCH_NAME" --sort=-refname | head -n 1)
          if [ -z "$EXISTING_BRANCH" ]
          then
            switched="false"
          else
            git checkout --track $EXISTING_BRANCH
            switched="true"
          fi
          echo "switched=$switched" >> $GITHUB_OUTPUT

      - name: Build metadata-cli
        run: |
          cargo install subxt
          subxt metadata --format bytes --url wss://rococo-rpc.polkadot.io:443 > essentials/assets/rococo_metadata.scale
          subxt metadata --format bytes --url wss://kusama-rpc.polkadot.io:443 > essentials/assets/kusama_metadata.scale
          subxt metadata --format bytes --url wss://rpc.polkadot.io:443 > essentials/assets/polkadot_metadata.scale

      - name: Commit changes if PR exists
        if: ${{ steps.checkout-pr.outputs.switched == 'true' }}
        using: "composite"
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update metadata" || true
          git push

      - name: Create Pull Request if not exist
        if: ${{ steps.checkout-pr.outputs.switched == 'false' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: add unsigned QR codes
          branch: ${{ $BRANCH_NAME }}
          delete-branch: true
          base: master
          title: '[Automated] Update metadata'
